### PR TITLE
Update Daikin-protocol-EHYHBX08AAV3.md

### PR DESCRIPTION
**Pull request by buuhsmead**
E35002F 01 ON
E35002F 00 OFF
Only in LWT Mode

### CODE REVIEW

**Comment by buuhsmead** [comment]
Also mentioned in 'doc/Commands-Eseries.md'.

**Comment by Arnold-n** [comment]
Thanks - but I'd like to complete the overall picture as I am not sure this is just only in LWT mode: there are 3 parameters in packet 0x35 that can be written: 0x2D, 0x2F, and 0x31. I think 0x2F works (in LWT mode), 0x2F and 0x31 are both needed (in RT mode), and I am not sure when 0x2D is useful. What are your findings?

**Comment by buuhsmead** [comment]
I think I have to take this PR back.
0x2F was the only one I checked in LWT mode.
Sadly enough, not good enough documented what the outcome is/was.

Not tested (yet) the combi 0x2F and 0x31.


Closing this PR as I am not sure anymore.
Thanks for your response.

**Comment by buuhsmead** [comment]
Closing this PR as I am not sure anymore.
Thanks for your response.

**Pull request closed without merging**
